file = open("shopping-list.txt", "w")
file.write("1. Apples\n")
file.write("2. Milk\n")
file.write("3. Oil\n")
file.write("4. Toenail cleaner\n")
file.write("5. Water\n")
file.close()
print("Shopping list saved to shopping-list.txt!")

file = open("shopping-list.txt", "r")
content = file.read()
print("\n=== My Shopping List ===")
print(content)
file.close()

file = open("shopping-list.txt", "a")
file.write("6. Queen size bed\n")
file.write("7. 44 candies\n")
file.close()